paths:
  /itens:
    get:
      summary: Lista todos os itens mágicos
      responses:
        '200':
          description: Lista de itens mágicos
    post:
      summary: Cria um novo item mágico
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                tipo:
                  type: string
                forca:
                  type: integer
                defesa:
                  type: integer
                personagemId:
                  type: string
      responses:
        '201':
          description: Item criado com sucesso
          
  /itens/{id}:
    get:
      summary: Buscar um item mágico por identificador
      parameters:
        - in: path
          name: id
          required: true
          description: ID do item mágico
          schema:
            type: string
      responses:
        '200':
          description: Item mágico encontrado
        '404':
          description: Item não encontrado
    delete:
      summary: Remover um item mágico
      parameters:
        - in: path
          name: id
          required: true
          description: ID do item mágico a ser removido
          schema:
            type: string
      responses:
        '200':
          description: Item removido
        '404':
          description: Item não encontrado

  /itens/personagem/{id}:
    get:
      summary: Lista todos os itens mágicos de um personagem
      parameters:
        - in: path
          name: id
          required: true
          description: ID do personagem
          schema:
            type: string
      responses:
        '200':
          description: Lista de itens mágicos do personagem
        '404':
          description: Personagem não encontrado

  /itens/personagem/{id}/amuleto:
    get:
      summary: Buscar o amuleto de um personagem
      parameters:
        - in: path
          name: id
          required: true
          description: ID do personagem
          schema:
            type: string
      responses:
        '200':
          description: Amuleto encontrado
        '404':
          description: Amuleto não encontrado
