paths:
  /personagens:
    post:
      summary: Cria um novo personagem
      description: |
        - A soma de Força + Defesa deve ser no máximo 10 pontos.
        - O personagem só pode ter **1** item do tipo **Amuleto**.
        - Classe deve ser: Guerreiro, Mago, Arqueiro, Ladino ou Bardo.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PersonagemInput'
      responses:
        '201':
          description: Personagem criado com sucesso
        '400':
          description: Requisição inválida - regras não respeitadas

components:
  schemas:
    PersonagemInput:
      type: object
      required:
        - nome
        - nomeAventureiro
        - classe
        - level
        - forca
        - defesa
      properties:
        nome:
          type: string
        nomeAventureiro:
          type: string
        classe:
          type: string
          enum: [Guerreiro, Mago, Arqueiro, Ladino, Bardo]
        level:
          type: integer
        forca:
          type: integer
          description: Soma com a defesa não pode ultrapassar 10
        defesa:
          type: integer
          description: Soma com a força não pode ultrapassar 10
        itensMagicos:
          type: array
          items:
            $ref: '#/components/schemas/ItemMagicoInput'

    ItemMagicoInput:
      type: object
      required:
        - nome
        - tipo
        - bonusForca
        - bonusDefesa
      properties:
        nome:
          type: string
        tipo:
          type: string
          enum: [Arma, Amuleto, Armadura, Anel]
        bonusForca:
          type: integer
        bonusDefesa:
          type: integer
